version: '2'
services:
  newoapp8-app:
    image: newoapp8
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://newoapp8-postgresql:5432/NewoApp8
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  newoapp8-postgresql:
    extends:
      file: postgresql.yml
      service: newoapp8-postgresql
